spring:
  rabbitmq:
    # host: 127.0.0.1
    # port: 5672
    # username: root
    # password: root
    # virtual-host: /
    # addresses: 127.0.0.1:5672 #多个以逗号隔开，和host功能一致
    connection-timeout: 5000 #连接超时，单位ms；0表示不限制
    requested-heartbeat: 60 #指定心跳超时，单位秒，0为不指定；默认60s
    publisher-returns: false #发布返回是否启用
    cache:
      channel: 
        size: 10 #缓存中保持的channel数量
        checkout-timeout: 3000 #当缓存数量被设置时，从缓存中获取一个channel的超时时间，单位毫秒；如果为0，则总是创建一个新channel
      connection:
        mode: channel #连接工厂缓存模式：CHANNEL 和 CONNECTION
        # size: 10 #缓存的连接数，只有是CONNECTION模式时生效;channel时不能配置size，否则报错
    ### listener
    listener:
       type: simple #两种类型，SIMPLE，DIRECT
       ## simple类型
       simple:
         concurrency: 1 #最小消费者数量
         maxConcurrency: 3 #最大的消费者数量
         missingQueuesFatal: false #是否停止容器当容器中的队列不可用
         ## 与direct相同配置部分
         autoStartup: true #是否自动启动容器
         acknowledgeMode: manual #表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
         prefetch: 3 #指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量
         defaultRequeueRejected: false #决定被拒绝的消息是否重新入队；默认是true（与参数acknowledge-mode有关系）
         idleEventInterval: 3000 #container events发布频率，单位ms
         ##重试机制
         retry: 
           stateless: true #有无状态
           enabled: false #是否开启
           maxAttempts: 3 #最大重试次数,默认3
           initialInterval: 1000 #重试间隔
           multiplier: 1 #对于上一次重试的乘数
           maxInterval: 10000 #最大重试时间间隔
       direct:
         consumersPerQueue: 3 #每个队列消费者数量
         missingQueuesFatal: false
         #...其余配置看上方公共配置
    ## template相关
    template:
      mandatory: false #是否启用强制信息；默认false
      receiveTimeout: 3000 #`receive()`接收方法超时时间
      replyTimeout: 3000 #`sendAndReceive()`超时时间
      exchange: #默认的交换机
      routingKey: #默认的路由
      defaultReceiveQueue: #默认的接收队列
      ## retry重试相关
      retry: 
        enabled: false #是否开启
        maxAttempts: 3 #最大重试次数
        initialInterval: 1000 #重试间隔
        multiplier: 1000 #失败间隔乘数
        maxInterval: 10000 #最大间隔 
    
