spring:
  config:
    activate:
      on-profile:
      - jackson
  jackson:    
    # property-naming-strategy: SNAKE_CASE # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式    
    property-naming-strategy: LOWER_CAMEL_CASE # 保证原始属性不被改变
    date-format: yyyy-MM-dd HH:mm:ss # 全局设置@JsonFormat的格式pattern    
    locale: zh # 当地时区    
    time-zone: GMT+8 # 设置全局时区
    default-property-inclusion: NON_NULL #不为空的属性才会序列化,具体属性可看JsonInclude.Include    
    serialization: # 常规默认,枚举类SerializationFeature中的枚举属性为key，值为boolean设置jackson序列化特性,具体key请看SerializationFeature源码
      INDENT_OUTPUT: true # 格式化输出
      WRITE_DATES_AS_TIMESTAMPS: false # 返回的java.util.date转换成timestamp
      FAIL_ON_EMPTY_BEANS: false # 对象为空时是否报错，默认true
      FAIL_ON_SELF_REFERENCES: false # 循环引用是否报错
      WRITE_SELF_REFERENCES_AS_NULL: true # 循环引用是否设置为null    
    deserialization: # 枚举类DeserializationFeature中的枚举属性为key，值为boolean设置jackson反序列化特性,具体key请看DeserializationFeature源码      
      FAIL_ON_UNKNOWN_PROPERTIES: false # 常用,json中含pojo不存在属性时是否失败报错,默认true
    # 枚举类MapperFeature中的枚举属性为key，值为boolean设置jackson ObjectMapper特性
    # ObjectMapper在jackson中负责json的读写、json与pojo的互转、json tree的互转,具体特性请看MapperFeature,常规默认即可
    mapper:      
      USE_GETTERS_AS_SETTERS: true # 使用getter取代setter探测属性，如类中含getName()但不包含name属性与setName()，传输的vo json格式模板中依旧含name属性;默认false
    # 枚举类JsonParser.Feature枚举类中的枚举属性为key，值为boolean设置jackson JsonParser特性
    # JsonParser在jackson中负责json内容的读取,具体特性请看JsonParser.Feature，一般无需设置默认即可
    parser:
      ALLOW_SINGLE_QUOTES: true # 是否允许出现单引号,默认false